imports:
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_notification.yml }
    - { resource: config.yml }

doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                metadata_cache_driver: apc
                query_cache_driver:
                  type: memcache
                  host: %memcache_host%
                  port: %memcache_port%
                  instance_class: Memcache
                result_cache_driver:
                  type: memcache
                  host: %memcache_host%
                  port: %memcache_port%
                  instance_class: Memcache
                auto_mapping: true
                mappings: ~
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
#monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: critical
#            handler:      grouped
#        grouped:
#            type:    group
#            members: [streamed, buffered]
#        streamed:
#            type:  stream
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#            channels: !doctrine
#        buffered:
#            type:    buffer
#            handler: swift
#        doctrine:
#            type: stream
#            path: %kernel.logs_dir%/doctrine_%kernel.environment%.log
#            level: debug
#            channels: doctrine
#        swift:
#            type:       %prod_monolog_type%
#            from_email: %prod_monolog_from_email%
#            to_email:   %prod_monolog_to_email%
#            subject:    %prod_monolog_subject%
#            level:      %prod_monolog_level%
