sonata_notification:
    backend: sonata.notification.backend.rabbitmq

    backends:
        doctrine:
            max_age:      86400     # max age in second
            pause:        500000    # delay in microseconds
            states:                 # raising errors level
                in_progress: 10
                error:       20
                open:        100
                done:        10000

        rabbitmq:
           exchange:     router
           connection:
               host:         %rabbitmq_host%
               user:         %rabbitmq_user%
               pass:         %rabbitmq_pass%
               port:         %rabbitmq_port%
               vhost:        %rabbitmq_vhost%
               console_url : http://rmzamora-sandbox.rmzamora.com:15672/api

    queues:
       - { queue: defaultQueue, recover: true, default: true, routing_key: the_routing_key, dead_letter_exchange: 'my.dead.letter.exchange'}

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~
                    ApplicationSonataNotificationBundle: ~
