sonata_notification:
    #backend: sonata.notification.backend.runtime
    backend: sonata.notification.backend.postpone

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~
                    ApplicationSonataNotificationBundle: ~
